[package]
name = "rust_python_bindings"
version = "0.1.0"
authors = ["pseres <peet.seres@gmail.com>"]

[lib]
name = "hello_rust"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
